### PR TITLE
Some small quality of life changes

### PR DESCRIPTION
**Pull request by Mews**
## Changes
- Changed the foreground color of the buttons from black to white because it was unreadable otherwise
- Added support for using the mouse scroll wheel for scrolling the canvas

### CODE REVIEW

**Comment by mpiele** [comment]
What os did you test this on? The scrolling won't work for me. Also, button foreground isn't changing.

**Comment by Mews** [comment]
I tested it on windows 11 on a virtual environment, but it should work on any os.
Did you clone my fork?

**Comment by mpiele** [comment]
It was a problem on my end, your code is alright.

**Comment by Mews** [comment]
Will you merge this pull request then @mpiele

**Comment by mpiele** [comment]
Yes, I was just running some test and playing with what you wrote.

**Pull request merged**
